rules:
  - id: codacy.tools-configs.terraform.aws.security.aws-subnet-has-public-ip-address.aws-subnet-has-public-ip-address
    # Attempt to ignore this rule for the networking module path
    paths-ignore:
      - terraform/modules/networking/main.tf

# Note: Semgrep configuration syntax for path-based ignores can vary by
# Semgrep/Codacy runner version. If this doesn't suppress the finding, we
# can alternatively add a `.semgrepignore` with the exact path or configure
# the rule exclusion in Codacy's project settings.
