extends: default

ignore: |
  .codacy/
  # Ignore node_modules for web
  web/node_modules/
  # Ignore .next build directory
  web/.next/

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
  comments:
    min-spaces-from-content: 1
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off'] # Added 'on'/'off' for flexibility
